### ISSUE TITLE
Produces error in ST3 on OSX

### ISSUE THREAD

**Issue by joostrijneveld** [ehuss/Sublime-Column-Select#2]
After installing the package and triggering column_select, I get the following error in the console
`TypeError: run_() takes 2 positional arguments but 3 were given`
I've tried rebinding to different keys, but the error persists.

**Comment by ehuss** [comment]
There are separate versions for ST2 vs ST3.  It looks like you installed the wrong version.  How did you install it?  I assume you are using Sublime 3.

**Comment by joostrijneveld** [comment]
That sounds good. Yeah, I'm using Sublime 3. I called `Package control: install package`, searched for `column select` and hit enter. When I then press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>up</kbd>, I get `TypeError: run_() takes 2 positional arguments but 3 were given`.

**Comment by ehuss** [comment]
Thanks for the report.  It looks like the setup in Package Control got messed up so that it was no longer pointing to the s3 branch.  I just checked in a change so that it should work in Sublime 2 or 3.

**Comment by joostrijneveld** [comment]
Thanks, that fixed it! Nice!
